### ISSUE TITLE
DEFAULT: parameter not set during installation

### ISSUE THREAD

**Issue by xobs** [proppy/conda-eda#5]
When installing the latest nightly, it exits with a return code of `2` along with the error `./mixed-signal-0-Linux-x86_64.sh: 340: DEFAULT: parameter not set`

This is from the installer released 2023-02-09:

```
(DFFRAM) user@Ondo:/si$ ./mixed-signal-0-Linux-x86_64.sh

Welcome to mixed-signal 0

mixed-signal will now be installed into this location:
/home/user/mixed-signal

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/user/mixed-signal] >>> /si/bin
PREFIX=/si/bin
Unpacking payload ...

Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
patching file share/pdk/sky130A/libs.tech/klayout/lvs/sky130.lylvs
patching file share/pdk/sky130A/libs.tech/klayout/pymacros/SKY130.lym
patching file share/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt
installation finished.
Do you wish the installer to initialize mixed-signal
by running conda init? [yes|no]
./mixed-signal-0-Linux-x86_64.sh: 340: DEFAULT: parameter not set
(DFFRAM) user@Ondo:/si$ echo $?
2
(DFFRAM) user@Ondo:/si$
```

**Comment by xobs** [comment]
This does appear to be caused by the `DEFAULT` variable getting referenced without being set.

Note that running with the `-b` flag doesn't trigger this particular code path.

**Comment by xobs** [comment]
On Ubuntu, `/bin/sh` is mapped to `dash`

**Comment by proppy** [comment]
I think that might be it, can you try to execute this interactively with `/bin/bash` and see if you encounter the same issue.?

**Comment by xobs** [comment]
I get the same issue with bash:

```
(base) user@Ondo:/si$ /bin/bash ./mixed-signal-0-Linux-x86_64.sh

Welcome to mixed-signal 0

mixed-signal will now be installed into this location:
/home/user/mixed-signal

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/user/mixed-signal] >>> /si/deleteme
PREFIX=/si/deleteme
Unpacking payload ...

Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
patching file share/pdk/sky130A/libs.tech/klayout/lvs/sky130.lylvs
patching file share/pdk/sky130A/libs.tech/klayout/pymacros/SKY130.lym
patching file share/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt
installation finished.
Do you wish the installer to initialize mixed-signal
by running conda init? [yes|no]
./mixed-signal-0-Linux-x86_64.sh: line 340: DEFAULT: unbound variable
(base) user@Ondo:/si$ echo $?
1
(base) user@Ondo:/si$
```

**Comment by proppy** [comment]
```
by running conda init? [yes|no]
./mixed-signal-0-Linux-x86_64.sh: line 340: DEFAULT: unbound variable
```
did you answer yes or no here?

**Comment by xobs** [comment]
I wasn't given the option to answer -- it exited immediately when that line appeared

**Comment by proppy** [comment]
ah, that looks like https://github.com/conda/constructor/issues/635

**Comment by proppy** [comment]
and it should be fixed with the latest version of constructor that was published 17 hours ago :)
https://github.com/conda/constructor/releases/tag/3.4.3

**Comment by proppy** [comment]
but since it didn't land yet in https://anaconda.org/main/constructor/files the latest build still doesn't have it.

**Comment by proppy** [comment]
bumped it in df622b0aa55fe0da2cb6f9a38a780c260345b70d and rebuilding new versions of the installers https://github.com/proppy/conda-eda/actions/runs/4140254532

**Comment by xobs** [comment]
This is still happening in https://github.com/proppy/conda-eda/releases/tag/v0.0-1436-gdf622b0

**Comment by proppy** [comment]
ah yes, for some reason the older version of constructor still get used:
```
    constructor-3.4.2+6.g15c6150|          py310_0         202 KB  ctools/label/dev

```

**Comment by proppy** [comment]
Giving it another go:
https://github.com/proppy/conda-eda/actions/runs/4140634760

**Comment by xobs** [comment]
This is now solved. Thank you!
